# Generated by Django 5.1.3 on 2024-11-11 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.TextField()),
                ('edad', models.IntegerField()),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Modelos.docente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Modelos.estudiantes')),
            ],
        ),
    ]
